django/api/services/vin_decoder.py

Changelog:
- Re-enabled for more than 50 rows
- pycodestyle

CTHUB-60: Allowed multiple pages for parsing

---

react/package.json
react/src/App.js
react/src/Login.js
react/src/icbc_data/IcbcDataContainer.js
react/src/icbc_data/router.js
react/src/keycloak.js

Changelog:
- Fixed an issue where you're always redirected back to the default url without using <Link>
- Should now retain your url even after logging in
- Fixed history push

Redirect fix

---

django/api/settings.py

Changelog:
- Allowed environment variable for django secret key

Made secret key as an environment variable

---

django/api/services/speciality_use_vehicle_incentives.py

adds filllna to 0 for numeric columns

partial fix: cthub 122 - upload for SUVI

---

README.md
django/README.md
django/api/services/arc_project_tracking.py
django/api/services/charger_rebates.py
django/api/services/hydrogen_fueling.py
django/api/viewsets/upload.py
docker-compose.yml
keycloak.env
keycloak/Dockerfile
react/src/uploads/UploadContainer.js

-removes unused services from dockerfile
-updates readme
-fixes error message on frontend
-adds more specific error handling on backend to upload and 3 scripts it calls
-moves try to outside of spreadsheet row iteration

Feat: Cthub 146 -  upload feedback

---

django/api/serializers/permission.py
django/api/serializers/user.py
django/api/urls.py
django/api/viewsets/user.py
react/src/app/styles/App.scss
react/src/app/styles/Users.scss
react/src/app/styles/index.scss
react/src/uploads/UploadContainer.js
react/src/uploads/components/UploadPage.js
react/src/users/UsersContainer.js
react/src/users/components/UsersPage.js
react/src/users/routes.js

adds backend for retrieving users, permissions
lists on frontend
no styling or creating/updating yet

Feat Cthub 168 PARTIAL admin page

---

react/src/app/styles/App.scss
react/src/app/styles/FileUpload.scss
react/src/app/styles/Users.scss
react/src/uploads/UploadContainer.js
react/src/uploads/components/FileDrop.js
react/src/uploads/components/FileDropArea.js
react/src/uploads/components/UploadPage.js
react/src/users/components/UsersPage.js

feat: frontend changes for upload and user admin
wireframe: https://preview.uxpin.com/a42f45b03540bc277cb03b7c5a178d9ea7ffd2fd#/pages/165706530?mode=m

CTHUB - Frontend styling for upload and user permissions page

---

react/src/users/components/UsersPage.js

fix: aligns names vertically in row

CTHUB - admin css idir vertical alignment fix

---

django/api/decorators/permission.py
django/api/serializers/user.py
django/api/services/permissions.py
django/api/services/user.py
django/api/viewsets/user.py
react/package.json
react/src/uploads/UploadContainer.js
react/src/users/UsersContainer.js
react/src/users/components/UsersPage.js
react/src/users/routes.js

adds functionality for saving new users and updating permissions of users

feat: CTHUB 198 - save/update users

---

react/src/uploads/UploadContainer.js
react/src/uploads/components/FileDrop.js
react/src/uploads/components/FileDropArea.js
react/src/uploads/components/UploadPage.js

feat: removes upload message when new dataset is selected or file is dropped

feat CTHUB 212 : clear upload message

---

README.md
django/api/decorators/permission.py
django/api/serializers/user.py
django/api/services/generic.py
django/api/services/permissions.py
django/api/services/user.py
django/api/viewsets/user.py
react/src/app/styles/App.scss
react/src/app/styles/FileUpload.scss
react/src/uploads/UploadContainer.js
react/src/uploads/components/FileDrop.js
react/src/uploads/components/FileDropArea.js
react/src/uploads/components/UploadPage.js
react/src/users/UsersContainer.js
react/src/users/components/UsersPage.js
react/src/users/routes.js

remarks:
(1) I noticed that when displaying/saving the list of users/permissions, the number of calls to the database were increasing along with the number of users/permissions, so I refactored it so that a constant number of calls are made; this should make it more scalable.
(2) I also added some instructions in the README about rebasing

feat: 210 - page refinements + cleanup

---

django/api/viewsets/user.py
react/src/app/components/AlertDialog.js
react/src/uploads/UploadContainer.js
react/src/uploads/components/UploadPage.js
react/src/users/UsersContainer.js
react/src/users/components/UsersPage.js
react/src/users/routes.js

-users can now be deleted by pressign red x. Modal appears (reuses alert dialogue component). 
-current user's X will be grey and disabled with a tooltip. Backend checks for current user as well.

feat: CTHUB 248 -Delete user

---

django/api/viewsets/upload.py

- Removing dataset from dropdown to be added back later

Task: Remove Dataset from Dropdown

---

frontend/src/users/UsersContainer.js
frontend/src/users/components/UsersPage.js

- Clearing text box on button click & sorting list when adding users

Task: Admin Page Refinements #255

---

django/api/tests/test_spreadsheet_uploader.py

- Backend tests for the uploader service

Task: Backend Tests for Uploader #165

---

django/api/viewsets/upload.py
frontend/src/uploads/UploadContainer.js

adds messages to icbc vins upload in import data function, adds basic error messaging to frontend in case errors don't have our standard format

fix: CTHUB 297 Adds success/error message to icbc vin upload

---

frontend/src/app/utilities/useAxios.js

feat: adds redirect to login page if user attempts any axios call after timing out

Feat: CTHUB 304 Redirect after timeout

---

frontend/src/users/UsersContainer.js
frontend/src/users/components/UsersPage.js

feat: disables save button on user permissions until any permission is changed

CTHUB 305: feat - admin panel - grey out save button if nothing has changed

---

django/api/services/spreadsheet_uploader_prep.py

feat: adds preposition capitalization logic

feat: CTHUB 316 - GER/SUVI Consistent prepositions and articles

---

django/api/services/spreadsheet_uploader_prep.py

- Adding prep function to alter manufacturer names to have more readable casing

Task: Adjust Manufacturer Names #317

---

django/api/services/spreadsheet_uploader.py
django/api/services/spreadsheet_uploader_prep.py
django/api/viewsets/upload.py
frontend/src/uploads/UploadContainer.js
frontend/src/uploads/components/UploadPage.js

-Similar sounding names are displayed to the user in a warning before the final upload
User can ignore the warning and proceed to the upload
if the user cancels then no records get inserted and the user can make changes to their spreadsheet before proceeding. If they proceed it inserts the records.

feat: 328 -  GER Typo checker for Applicant Name

---

django/api/services/spreadsheet_uploader.py

- Added numeric string alteration to remove commas and empty spaces.  
- Removed duplicate type casting.
- Refactored end of loop error checking code.

Task - Coerce Numeric Strings to Correct Values #320

---

django/api/bcngws_constants.py
django/api/services/bcngws.py
django/api/services/spreadsheet_uploader.py
django/api/services/spreadsheet_uploader_prep.py
django/api/settings.py

-checks spreadsheet cities against placenames api and return matching names

feat : 322 - list of locations (api)

---

django/api/constants.py
django/api/services/spreadsheet_uploader.py
django/api/services/spreadsheet_uploader_prep.py
frontend/src/uploads/UploadContainer.js

- Adding phone number verification method
- Updating validation functions to correctly identify invalid rows
- Added phone number validation to warning popup

Task: Phone Number Verification Method #325

---

django/api/constants.py
django/api/services/spreadsheet_uploader_prep.py

fix: updates typo checker to pass row numbers

feat: updates typo checker to pass row numbers

---

django/api/viewsets/upload.py

updates request.data.get to expect replaceData rather than replace

fix 365 - replace data not working

---

django/api/constants/constants.py
django/api/constants/misc.py
django/api/services/spreadsheet_uploader_prep.py

- Adding function to check if values in fields are valid

Task: Restrict Field Values #343

---

frontend/src/app/components/AlertDialog.js
frontend/src/uploads/components/UploadIssues.js
frontend/src/uploads/components/UploadIssuesDetail.js

- Frontend fixes for the error notification refactor

Task: Error/Warning Notification Fix #365

---

django/api/services/spreadsheet_uploader_prep.py

- Added check for string length being long enough to apply lambda funct…ion to prevent errors

Fix: GER Uploader Error Fix #379

---

django/api/constants/constants.py

- Temporarily disabling the location_checker function to test for timeout errors

Timeout Error Bug Fix

---

django/api/services/spreadsheet_uploader_prep.py

- Checking for empty values in phone numbers and emails to avoid flagging them with an incorrect warning

Task: Remove Incorrect Warnings #384

---

django/api/services/spreadsheet_uploader.py
django/api/services/spreadsheet_uploader_prep.py

- Added logic to include the expected values for restricted fields
- Added logic for type errors to display in a more human readable way
- Removed unnecessary logic
- Updated format_case function to handle null values
- Added datetime error check

Task: Uploader Error Descriptions #2208

---

django/api/migrations/0038_addregions.py

- Added migration for regions table data

Task: Economic Regions Table Data #381

---

django/api/services/spreadsheet_uploader.py
frontend/src/uploads/UploadContainer.js
frontend/src/uploads/components/UploadIssues.js
frontend/src/uploads/components/UploadIssuesDetail.js

- Added new critical error type
- Added backend functionality to check for missing headers or spreadsheet and return critical error if true
- Updated frontend to accomodate new critical error type

Fix: Uploader Critical Errors #400

---

frontend/src/app/styles/App.scss
frontend/src/app/styles/variables.scss
frontend/src/uploads/components/FileDrop.js
frontend/src/uploads/components/FileDropArea.js
frontend/src/uploads/components/UploadPage.js

adds tooltip
styles download template button

Task: 403 - tooltip, download template button

---

django/api/services/spreadsheet_uploader_prep.py
frontend/src/uploads/UploadContainer.js
frontend/src/uploads/components/UploadIssuesDetail.js
frontend/src/uploads/components/UploadPage.js

- Removing duplicate formatting
- Fixing returned structure of region error info
- Updating alert to only display on successful import

Error Descriptions Fix

---

django/api/services/spreadsheet_uploader.py
frontend/src/app/components/AlertDialog.js
frontend/src/uploads/UploadContainer.js
frontend/src/uploads/components/FileDrop.js
frontend/src/uploads/components/FileDropArea.js
frontend/src/uploads/components/UploadIssues.js
frontend/src/uploads/components/UploadPage.js

-adds failed uploads list to the the list of files below the file drop area. X button is text that shows 'failed upload' and will continue to display when user uploads a different file
-changes popup text if critical error
-redesign for banner display for failed uploads
- adds condition for displaying error details, critical errors now don't show row/column information just one statement

feat: 398 -  Missing column and/or sheet error

---

django/api/constants/constants.py
django/api/services/spreadsheet_uploader_prep.py

- Adding prep function that formats postal codes and validates them if asked to do so

Task: Postal Code Formatting #385

---

frontend/src/uploads/UploadContainer.js
frontend/src/uploads/components/FileDrop.js
frontend/src/uploads/components/FileDropArea.js
frontend/src/uploads/components/UploadIssues.js
frontend/src/uploads/components/UploadIssuesDetail.js
frontend/src/uploads/components/UploadPage.js

-cancel button on both popup and banner alerts now removes warning messages and clears the uploadList
-success dialogue appears after ignoring warnings
-linting

CTHUB 419 - Cancel uploads with warnings/errors

---

django/api/constants/misc.py

- Removing value checking on vehicle type column, now it only checks if a value exists

Fix: CVP Data Vehicle Type Fix

---

frontend/src/app/components/AlertDialog.js
frontend/src/uploads/components/FileDropArea.js

- Added popup dialog to delete selected dataset
- Added optional styling to confirmation button in AlertDialog component

Task: Confirmation Dialog for Deleting Selected Dataset #404

---

django/api/services/spreadsheet_uploader.py

fix: adds an extra 1 row to the row index to account for starting at 0

CTHUB - Missing error row number is off by one #416

---

django/api/services/spreadsheet_uploader.py

- Making error for expected integer type read as expected numeric for clarity

Fix: Rewording Expected Integer Type Error #415

---

frontend/src/uploads/UploadContainer.js

- Making alert message only appear on successful upload to allow for new alert system to display errors in order to reduce confusion

Task: Remove Old Notification #433

---

django/api/settings.py
django/api/viewsets/upload.py
django/requirements.txt
frontend/src/uploads/UploadContainer.js

- Adding drf camel case to requirements.txt
- Updating frontend/backend to accomodate it

Task: Install DRF Camel Case #432

---

frontend/src/uploads/UploadContainer.js
frontend/src/users/UsersContainer.js
frontend/src/users/components/UsersPage.js

- Fixing syntax issues with drf camel case to allow admin panel to appear

Fix: DRF Camel Case Causing Admin Panel Not To Render

---

django/api/services/minio.py
django/api/services/spreadsheet_uploader.py
django/api/viewsets/upload.py
frontend/src/uploads/UploadContainer.js
frontend/src/uploads/components/CleanDatasetDownload.js
frontend/src/uploads/components/UploadPage.js
frontend/src/uploads/routes.js

- Adding presigned url function for clean datasets to be downloaded from minio
- Adding clean dataset download for uploads that don't have errors

Task: Clean Dataset Download #388

---

django/api/services/spreadsheet_uploader.py
django/api/services/spreadsheet_uploader_prep.py
frontend/src/uploads/UploadContainer.js
frontend/src/uploads/components/UploadIssuesDetail.js

- Updating backend/frontend casing to match new DRF camel case library.

Task: Casing #445
